"""Tests for the adapter installation helpers."""

from __future__ import annotations

from pathlib import Path

from adzekit.modules.adapters import (
    install_claude_code,
    status_claude_code,
    uninstall_claude_code,
)
from adzekit.modules.adapters_hermes import (
    build_skill_pack,
    install_hermes,
    status_hermes,
    translate_soul_to_hermes,
)


# --- Claude Code adapter ----------------------------------------------------


def test_claude_code_install_populates_target(tmp_path, workspace):
    target = tmp_path / "fake-plugin"
    result = install_claude_code(target_plugin_dir=target)
    assert result["adapter"] == "claude-code"
    assert (target / ".claude-plugin" / "plugin.json").exists()
    assert (target / "agents").is_dir()
    assert (target / "commands").is_dir()
    assert (target / "skills").is_dir()
    # All core skills present in the mirrored target.
    skill_files = list((target / "skills").glob("*.md"))
    # The README in skills/ is excluded from the skill count we copied,
    # but mirrored as part of the directory copy.
    skill_names = {p.name for p in skill_files} - {"README.md"}
    assert "daily-start.md" in skill_names
    assert "inbox-triage.md" in skill_names


def test_claude_code_status_reports_installed(tmp_path):
    target = tmp_path / "fake-plugin"
    install_claude_code(target_plugin_dir=target)
    status = status_claude_code(target_plugin_dir=target)
    assert status["installed"] is True
    assert status["skills"] > 0
    assert status["commands"] > 0
    assert status["agents"] > 0


def test_claude_code_status_reports_not_installed(tmp_path):
    status = status_claude_code(target_plugin_dir=tmp_path / "nonexistent")
    assert status["installed"] is False
    assert status["skills"] == 0


def test_claude_code_uninstall_removes_target(tmp_path):
    target = tmp_path / "fake-plugin"
    install_claude_code(target_plugin_dir=target)
    assert target.exists()
    result = uninstall_claude_code(target_plugin_dir=target)
    assert result["removed"] is True
    assert not target.exists()


def test_claude_code_install_is_idempotent(tmp_path):
    target = tmp_path / "fake-plugin"
    install_claude_code(target_plugin_dir=target)
    skills_first = sorted((target / "skills").glob("*.md"))
    install_claude_code(target_plugin_dir=target)
    skills_second = sorted((target / "skills").glob("*.md"))
    assert [p.name for p in skills_first] == [p.name for p in skills_second]


# --- Hermes SOUL.md translation --------------------------------------------


def test_translate_soul_missing_returns_none(workspace, tmp_path):
    dest = tmp_path / "SOUL.md"
    result = translate_soul_to_hermes(workspace, dest=dest)
    assert result is None
    assert not dest.exists()


def test_translate_soul_concatenates_sources_verbatim(workspace, tmp_path):
    """Phase B: SOUL.md is whole-file concat of soul.md + role-context.md.

    Hermes treats SOUL.md as a plain markdown file with no schema, so the
    adapter preserves source content verbatim and only adds a small
    generated header noting provenance.
    """
    soul = workspace.knowledge_dir / "soul.md"
    soul.write_text(
        "# Soul\n\n"
        "## Voice\n"
        "- Direct.\n\n"
        "## Deep work hours\n"
        "09:00-11:00\n",
        encoding="utf-8",
    )
    role = workspace.knowledge_dir / "role-context.md"
    role.write_text(
        "# Role Context\n\n"
        "Senior engineer working on agent runtimes.\n",
        encoding="utf-8",
    )
    dest = tmp_path / "SOUL.md"
    result = translate_soul_to_hermes(workspace, dest=dest)
    assert result == dest
    text = dest.read_text(encoding="utf-8")
    # Header comment surfaces provenance without polluting the rendered text.
    assert "<!-- Generated by AdzeKit" in text
    # Source content appears verbatim — no Hermes-hints block, no section
    # restructuring, no schema imposition.
    assert "## Voice" in text
    assert "- Direct." in text
    assert "## Deep work hours" in text
    assert "09:00-11:00" in text
    assert "Senior engineer working on agent runtimes." in text
    # The old over-engineered "## Hermes hints" block is gone.
    assert "## Hermes hints" not in text


def test_translate_soul_handles_only_one_source(workspace, tmp_path):
    """If role-context.md is missing, the concat still works with just soul.md."""
    (workspace.knowledge_dir / "soul.md").write_text(
        "# Soul\n\n## Voice\n- Direct.\n", encoding="utf-8",
    )
    dest = tmp_path / "SOUL.md"
    result = translate_soul_to_hermes(workspace, dest=dest)
    assert result == dest
    text = dest.read_text(encoding="utf-8")
    assert "- Direct." in text


# --- Hermes pack building ---------------------------------------------------


def test_build_skill_pack_emits_per_skill_directories(tmp_path):
    """Phase B: each skill becomes <pack>/<skill>/SKILL.md per agentskills.io."""
    pack = tmp_path / "pack"
    result = build_skill_pack(pack_dir=pack)
    assert pack.exists()
    # No more pack.toml — that wasn't a Hermes concept.
    assert not (pack / "pack.toml").exists()
    # Each skill is a directory with SKILL.md inside.
    for skill_name in ("daily-start", "inbox-triage", "distill"):
        skill_dir = pack / skill_name
        assert skill_dir.is_dir(), f"missing skill dir: {skill_name}"
        skill_file = skill_dir / "SKILL.md"
        assert skill_file.exists(), f"missing SKILL.md in {skill_name}/"
        text = skill_file.read_text(encoding="utf-8")
        # YAML frontmatter per agentskills.io standard.
        assert text.startswith("---\n")
        assert f"name: {skill_name}\n" in text
        assert "description: " in text
        assert "version: " in text
        assert "author: AdzeKit\n" in text
        assert "license: MIT\n" in text
        # Frontmatter is closed with a `---` line.
        assert "\n---\n" in text


def test_build_skill_pack_rebuild_cleans_stale_directories(tmp_path):
    """Rebuilding into a populated pack dir drops stale skills + old flat layout."""
    pack = tmp_path / "pack"
    pack.mkdir()
    # Pre-existing stale skill directory (left over from a previous version).
    stale_dir = pack / "old-skill"
    stale_dir.mkdir()
    (stale_dir / "SKILL.md").write_text("---\nname: old-skill\n---\n", encoding="utf-8")
    # Pre-existing flat-layout skill file (pre-B rebuild).
    stale_flat = pack / "old-flat.md"
    stale_flat.write_text("# stale flat\n", encoding="utf-8")
    # Pre-existing obsolete pack.toml from the pre-B rebuild.
    stale_toml = pack / "pack.toml"
    stale_toml.write_text("obsolete\n", encoding="utf-8")

    build_skill_pack(pack_dir=pack)

    assert not stale_dir.exists()
    assert not stale_flat.exists()
    assert not stale_toml.exists()


# --- Hermes install end-to-end ---------------------------------------------


def test_install_hermes_stages_pack(workspace, tmp_path, monkeypatch):
    # Redirect the staged pack dir + soul output so the test is hermetic.
    pack_dir = tmp_path / "stage"
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_PACK_DIR", pack_dir,
    )
    # Point HERMES_HOME at a non-existent dir so the installer stays in
    # stage mode (doesn't try to mirror into ~/.hermes).
    fake_home = tmp_path / "no-hermes"
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_HOME", fake_home,
    )
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_SOUL_PATH",
        fake_home / "SOUL.md",
    )

    (workspace.knowledge_dir / "soul.md").write_text(
        "# Soul\n\n## Voice\n- Direct.\n", encoding="utf-8",
    )

    result = install_hermes(workspace)
    assert result["adapter"] == "hermes"
    assert Path(result["pack_dir"]) == pack_dir
    assert result["hermes_skills_dir"] is None  # Hermes not detected
    assert result["soul_path"] is not None
    assert (pack_dir / "SOUL.md").exists()
    # Per-skill directory layout, not flat.
    assert (pack_dir / "daily-start" / "SKILL.md").exists()
    assert (pack_dir / "inbox-triage" / "SKILL.md").exists()
    # No pack.toml.
    assert not (pack_dir / "pack.toml").exists()
    assert len(result["skills"]) > 0


def test_install_hermes_mirrors_into_hermes_home(workspace, tmp_path, monkeypatch):
    """When ~/.hermes/ exists, the pack is also mirrored into ~/.hermes/skills/adzekit/."""
    pack_dir = tmp_path / "stage"
    fake_home = tmp_path / "dot-hermes"
    fake_home.mkdir()  # Hermes "detected"
    fake_skills = fake_home / "skills" / "adzekit"
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_PACK_DIR", pack_dir,
    )
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_HOME", fake_home,
    )
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_SOUL_PATH", fake_home / "SOUL.md",
    )
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_SKILLS_DIR", fake_skills,
    )

    (workspace.knowledge_dir / "soul.md").write_text(
        "# Soul\n## Voice\n- Direct.\n", encoding="utf-8",
    )
    result = install_hermes(workspace)
    assert result["hermes_skills_dir"] == str(fake_skills)
    assert (fake_skills / "daily-start" / "SKILL.md").exists()
    assert (fake_home / "SOUL.md").exists()


def test_status_hermes_reports_unstaged_cleanly(workspace, tmp_path, monkeypatch):
    pack_dir = tmp_path / "absent-pack"
    fake_home = tmp_path / "no-hermes"
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_PACK_DIR", pack_dir,
    )
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_HOME", fake_home,
    )
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_SOUL_PATH",
        fake_home / "SOUL.md",
    )
    monkeypatch.setattr(
        "adzekit.modules.adapters_hermes.HERMES_SKILLS_DIR",
        fake_home / "skills" / "adzekit",
    )
    result = status_hermes(workspace)
    assert result["pack_present"] is False
    assert result["hermes_detected"] is False
    assert result["hermes_skills_installed"] is False
