"""``adze``: five verbs. No AI, no network except ``git`` in ``sync``."""

from __future__ import annotations

import argparse
import sys
from datetime import date

from adzekit import __version__, records
from adzekit.shed import Workspace, WorkspaceError, block_version, init
from adzekit.sync import sync


def _each(args: argparse.Namespace, *, always_header: bool = False):
    """Yield each target shed, with a header when there are several (or when asked)."""
    sheds = Workspace.targets(args.workspace)
    for i, ws in enumerate(sheds):
        if len(sheds) > 1 or always_header:
            print(f"{'' if i == 0 else chr(10)}== {ws.name}  ({ws.root})")
        yield ws


def cmd_init(args: argparse.Namespace) -> None:
    ws, changed = init(args.path or args.workspace or ".", remote=args.remote, name=args.name)
    print(f"Shed {ws.name}: {ws.root}")
    for item in changed:
        print(f"  {item}")
    if not changed:
        print("  up to date")
    print("Next: `adze sync`.")


def cmd_today(args: argparse.Namespace) -> None:
    for ws in _each(args):
        _today(ws)


def _today(ws: Workspace) -> None:
    result = records.today(ws, date.today())
    rel = result.path.relative_to(ws.root)
    if result.swept:
        print(f"Swept {len(result.swept)} ticked loop(s) to the archive.")
    if result.archived:
        print(f"Archived {len(result.archived)} daily note(s) older than "
              f"{ws.setting('archive_daily_days')} days.")
    if result.created:
        print(f"Created {rel}" + (f", carried {len(result.carried)}" if result.carried else ""))
    for task in result.left_behind:
        print(f"  over the daily cap, not carried: {task}")
    print()
    print(result.path.read_text(encoding="utf-8"), end="")


def cmd_status(args: argparse.Namespace) -> None:
    for ws in _each(args, always_header=True):
        _status(ws)


def _status(ws: Workspace) -> None:
    today = date.today()
    h = records.health(ws, today)
    note = ws.daily_path(today)
    if note.is_file():
        open_, done = records.intentions(note.read_text(encoding="utf-8"))
        day = f"{len(done)}/{len(open_) + len(done)} intentions done"
    else:
        day = "no note yet (adze today)"
    cap = ws.setting("max_active_projects")
    print(f"Today:     {day}")
    print(f"Loops:     {len(h.loops)} open, {len(h.overdue)} overdue, {len(h.stale)} stale")
    over = "  OVER CAP" if len(h.projects) > cap else ""
    print(f"Projects:  {len(h.projects)}/{cap} active{over}, {len(h.quiet)} quiet")
    for loop in h.overdue:
        print(f"  overdue: {loop.title}")
    written = block_version(ws)
    if written and written != __version__:
        print(f"  AGENTS.md was generated by {written}; run `adze init` to refresh it.")


def cmd_review(args: argparse.Namespace) -> None:
    for ws in _each(args):
        path, created = records.write_review(ws, args.date)
        print(f"{'Created' if created else 'Exists'}: {path.relative_to(ws.root)}")


def cmd_sync(args: argparse.Namespace) -> None:
    """Sync every target; one shed failing doesn't stop the others."""
    failures = []
    for ws in _each(args):
        try:
            for step in sync(ws, args.message):
                print(step)
        except WorkspaceError as exc:
            print(f"adze: {exc}", file=sys.stderr)
            failures.append(ws.name)
    if failures:
        raise WorkspaceError(f"sync failed for: {', '.join(failures)}")


def _date(text: str) -> date:
    try:
        return date.fromisoformat(text)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"expected YYYY-MM-DD, got {text!r}") from exc


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="adze", description="Markdown habits for people "
                                     "and their agents.")
    parser.add_argument("--version", action="version", version=f"adze {__version__}")
    parser.add_argument("-w", "--workspace", metavar="SHED",
                        help="shed name or folder (default: the one you're in, else all)")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("init", help="create, join, or refresh a shed")
    p.add_argument("path", nargs="?")
    p.add_argument("--remote", help="git URL; clones it if the folder is empty")
    p.add_argument("--name", help="short name for this shed (default: folder name)")
    p.set_defaults(func=cmd_init)

    sub.add_parser("today", help="today's note: create, carry forward, sweep loops"
                   ).set_defaults(func=cmd_today)
    sub.add_parser("status", help="one-screen health check").set_defaults(func=cmd_status)

    p = sub.add_parser("review", help="write the week's review scaffold")
    p.add_argument("--date", type=_date, default=date.today(), help="any day in the week")
    p.set_defaults(func=cmd_review)

    p = sub.add_parser("sync", help="commit, rebase onto the remote, push")
    p.add_argument("-m", "--message")
    p.set_defaults(func=cmd_sync)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        args.func(args)
    except WorkspaceError as exc:
        print(f"adze: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
