"""Find, create, and refresh a shed.

Everything ``init`` writes is generated here from the same constants and
settings the rest of the code reads, so the instructions agents follow cannot
drift from the formats the CLI parses. Generated text lives between managed
markers and is rewritten on every ``init``; anything outside them is yours.
"""

from __future__ import annotations

import os
import re
import subprocess
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from adzekit import __version__

MARKER = ".adzekit"
DEFAULTS = {
    "max_active_projects": 3,
    "max_daily_tasks": 5,
    "stale_loop_days": 7,
    "stale_project_days": 14,
}

DAILY_DIR = "daily"
LOOPS_FILE = "loops/active.md"
LOOPS_ARCHIVE = "loops/archive.md"
PROJECTS_DIR = "projects"
REVIEWS_DIR = "reviews"
SKILLS_DIR = "skills"
RECORD_DIRS = ("daily", "loops", "projects", "knowledge", "reviews")


class WorkspaceError(Exception):
    """Raised when a shed cannot be found or used."""


def global_config_path() -> Path:
    return Path.home() / ".config" / "adzekit" / "config"


def read_kv(path: Path) -> dict[str, str]:
    """Parse ``key = value`` lines, ignoring blanks and ``#`` comments."""
    if not path.is_file():
        return {}
    values = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        key, sep, value = line.partition("=")
        if sep and not key.strip().startswith("#"):
            values[key.strip()] = value.strip()
    return values


def write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


@dataclass(frozen=True)
class Workspace:
    root: Path

    def __post_init__(self) -> None:
        object.__setattr__(self, "root", Path(self.root).expanduser().resolve())

    @classmethod
    def find(cls, explicit: str | Path | None = None) -> "Workspace":
        """Resolve the shed: flag, env, enclosing folder, then global config."""
        candidate = explicit or os.environ.get("ADZEKIT_WORKSPACE")
        if not candidate:
            here = Path.cwd().resolve()
            candidate = next((p for p in (here, *here.parents) if (p / MARKER).is_file()), None)
        if not candidate:
            config = read_kv(global_config_path())
            candidate = config.get("workspace") or config.get("shed")
        if not candidate:
            raise WorkspaceError("No shed found. Run `adzekit init PATH` first.")
        ws = cls(Path(candidate))
        if not (ws.root / MARKER).is_file():
            raise WorkspaceError(f"{ws.root} has no {MARKER} file. Run `adzekit init {ws.root}`.")
        return ws

    def setting(self, key: str) -> int:
        raw = read_kv(self.root / MARKER).get(key)
        try:
            return int(raw) if raw is not None else DEFAULTS[key]
        except ValueError:
            return DEFAULTS[key]

    def path(self, relative: str) -> Path:
        return self.root / relative

    def daily_path(self, day: date) -> Path:
        return self.root / DAILY_DIR / f"{day.isoformat()}.md"


# --- managed blocks ------------------------------------------------------


def _block(begin: str, end: str, body: str) -> str:
    return f"{begin}\n{body.strip()}\n{end}\n"


def upsert(path: Path, block: str, begin_prefix: str, end: str, *, tail: str = "") -> bool:
    """Replace the managed block in ``path``, or put it first. Returns True if changed."""
    old = path.read_text(encoding="utf-8") if path.is_file() else ""
    pattern = re.compile(re.escape(begin_prefix) + r".*?" + re.escape(end) + r"\n?", re.S)
    if pattern.search(old):
        new = pattern.sub(lambda _: block, old, count=1)
    elif old:
        new = block + "\n" + old
    else:
        new = block + tail
    if new == old:
        return False
    write_atomic(path, new)
    return True


def _md_markers() -> tuple[str, str, str]:
    prefix = "<!-- adzekit:begin"
    begin = f"{prefix} v{__version__} (generated by `adzekit init`; edits here are replaced) -->"
    return prefix, begin, "<!-- adzekit:end -->"


def _hash_markers() -> tuple[str, str, str]:
    prefix = "# adzekit:begin"
    return prefix, f"{prefix} v{__version__} (generated by `adzekit init`)", "# adzekit:end"


def block_version(ws: Workspace) -> str | None:
    """Version that last wrote AGENTS.md's managed block, if any."""
    agents = ws.path("AGENTS.md")
    text = agents.read_text(encoding="utf-8") if agents.is_file() else ""
    match = re.search(r"<!-- adzekit:begin v([\w.]+)", text)
    return match[1] if match else None


def agents_contract(ws: Workspace) -> str:
    s = ws.setting
    return f"""
# Shed

This folder is an AdzeKit shed: plain Markdown shared by a person and every agent
that helps them. It holds **records** (their state) and **skills** (how they want
recurring work done). Read this whole file before working here.

## Records

- `{DAILY_DIR}/YYYY-MM-DD.md` — one note per day with three sections:
  `## Intention` (at most {s("max_daily_tasks")} checkboxes), `## Log`, `## Reflection`.
- `{LOOPS_FILE}` — open commitments, one line each:
  `- [ ] (S) [YYYY-MM-DD] What I owe, to whom (YYYY-MM-DD)`. The first date is
  when it opened; the trailing one is optional and means due. Tick with `[x]`.
- `{LOOPS_ARCHIVE}` — ticked loops, moved here by `adzekit today`.
- `{PROJECTS_DIR}/*.md` — active projects, at most {s("max_active_projects")}. Parked
  work goes in `{PROJECTS_DIR}/backlog/`, finished work in `{PROJECTS_DIR}/archive/`
  (move the file). Each has `## Context` and a `## Log` of dated entries, newest first.
- `knowledge/*.md` — durable notes. Link with `[[note-name]]`; tag with `#kebab-case`.
- `{REVIEWS_DIR}/YYYY-Www.md` — weekly reviews and other reports.

## Skills

`{SKILLS_DIR}/*.md` are procedures. When I name one ("run daily start",
"/weekly-review"), read `{SKILLS_DIR}/<name>.md` and follow it. If I ask for
something I'll clearly ask for again, offer to save it as a new skill.

## Rules

1. **Sync first and last.** Run `adzekit sync` before you start and after you
   finish. If it reports a problem, stop and tell me.
2. **Edit the files directly**, in the formats above, in small changes. Git is
   the undo button.
3. **Keep it plain.** No frontmatter, IDs, or new folders unless I ask.
4. **Don't invent.** If it isn't in these files or a source you checked, say so.
5. **Date what you add.** Log entries start with `YYYY-MM-DD:`.
6. **Respect the limits.** When something new competes for a full daily list or
   the project cap, propose a trade-off instead of exceeding it.
7. **Close loops explicitly.** Tick it, or rewrite it with a new date and reason.
8. **Be brief.** I may be reading on a phone.

## CLI

`adzekit today` (create today's note, carry forward, sweep ticked loops),
`adzekit status`, `adzekit review` (weekly scaffold), `adzekit sync`. Nothing
else is needed. If the CLI isn't installed, the formats above are the contract.
"""


GITIGNORE = """
# Raw material stays local; link to it from projects instead.
stock/
*.tmp
.DS_Store
.obsidian/workspace*.json
# Shed settings and merge rules must travel with the shed.
!.adzekit
!.gitattributes
"""

# Records are append-heavy and line-oriented: keep both sides instead of
# stopping on a conflict. Instructions (AGENTS.md, skills) merge normally.
GITATTRIBUTES = "\n".join(f"{d}/**/*.md merge=union" for d in RECORD_DIRS)

SKILLS = {
    "daily-start": f"""# Daily start

**Goal:** today's note with intentions I actually chose.

1. Run `adzekit today`. Unfinished intentions carry forward; ticked loops move
   to the archive.
2. Read `{LOOPS_FILE}`. For each loop that is overdue or older than the stale
   threshold in `.adzekit`, ask me: act today, reschedule, or drop? One question
   at a time. Apply each answer to the loop line.
3. Write the chosen intentions under `## Intention`, most important first. If
   more compete than the cap allows, show me the trade-off.
4. Reply with the list and nothing else.
""",
    "daily-close": f"""# Daily close

**Goal:** leave nothing open in my head overnight.

1. Read today's note. Ask which intentions got done, and tick them.
2. Add a line to `{LOOPS_FILE}` for anything I promised someone today. Tick
   loops that got resolved.
3. Add a dated `## Log` entry to each project that moved.
4. Write two or three lines under `## Reflection`: what moved, what's stuck,
   the first thing to do tomorrow.
""",
    "weekly-review": f"""# Weekly review

**Goal:** every stale loop and quiet project gets a decision.

1. Run `adzekit review` to write this week's `{REVIEWS_DIR}/YYYY-Www.md`.
2. Walk me through each **Decide** item, one at a time. Loops: act, schedule,
   or drop. Projects: continue, backlog, or archive (move the file). Apply each
   answer as I give it.
3. If active projects exceed the cap, ask me what to park.
4. Draft up to three **Next week** checkboxes and let me edit them.
5. Ask me one reflection question; record the answer under `## Reflection`.
""",
    "capture": f"""# Capture

**Goal:** turn something messy (a thread, meeting notes, a memo) into the right
lines in the right files.

1. Pull out, quoting the source for each:
   - commitments (who owes what, by when) as lines in `{LOOPS_FILE}`;
   - progress and decisions as dated entries in the matching `{PROJECTS_DIR}/<slug>.md`;
   - durable facts as notes in `knowledge/`, linked with `[[...]]`.
2. Show me the planned edits as a short list; apply them once I confirm. One
   loop or one log line can go straight in.
3. Never create a project without asking.
4. Keep long originals out of notes: save them under `stock/<slug>/` and link.
""",
}


# --- init ----------------------------------------------------------------


def _git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True)


def init(root: str | Path, remote: str | None = None) -> tuple[Workspace, list[str]]:
    """Create or refresh a shed. Idempotent; never touches text outside managed blocks."""
    root = Path(root).expanduser().resolve()
    changed: list[str] = []

    if remote and (not root.exists() or not any(root.iterdir())):
        result = subprocess.run(["git", "clone", remote, str(root)], capture_output=True, text=True)
        if result.returncode != 0:
            raise WorkspaceError(f"git clone failed:\n{result.stderr.strip()}")
        changed.append(f"cloned {remote}")
        if _git(root, "rev-parse", "-q", "--verify", "HEAD").returncode != 0:
            _git(root, "symbolic-ref", "HEAD", "refs/heads/main")
    root.mkdir(parents=True, exist_ok=True)
    if _git(root, "rev-parse", "--is-inside-work-tree").returncode != 0:
        _git(root, "init", "-q", "-b", "main")
        changed.append("git init")
    if remote and not _git(root, "remote").stdout.split():
        _git(root, "remote", "add", "origin", remote)
        changed.append(f"remote origin → {remote}")

    ws = Workspace(root)
    marker = root / MARKER
    if not marker.exists():
        marker.write_text("".join(f"{k} = {v}\n" for k, v in DEFAULTS.items()), encoding="utf-8")
        changed.append(MARKER)

    prefix, begin, end = _md_markers()
    about = "\n## About me\n\n<!-- Who you are, what you work on, how you like answers. -->\n"
    if upsert(root / "AGENTS.md", _block(begin, end, agents_contract(ws)), prefix, end, tail=about):
        changed.append("AGENTS.md")
    for shim in ("CLAUDE.md", "GEMINI.md"):
        path = root / shim
        text = path.read_text(encoding="utf-8") if path.is_file() else ""
        if "@AGENTS.md" in text and prefix not in text:
            continue  # already imports the contract by hand
        if upsert(path, _block(begin, end, "@AGENTS.md"), prefix, end):
            changed.append(shim)

    prefix, begin, end = _hash_markers()
    for name, body in ((".gitignore", GITIGNORE), (".gitattributes", GITATTRIBUTES)):
        path = root / name
        old = path.read_text(encoding="utf-8") if path.is_file() else ""
        block = _block(begin, end, body)
        # Appended, not prepended: later gitignore rules win, so re-includes stick.
        if prefix in old:
            if upsert(path, block, prefix, end):
                changed.append(name)
        else:
            write_atomic(path, old + ("\n" if old and not old.endswith("\n") else "") + block)
            changed.append(name)

    loops = ws.path(LOOPS_FILE)
    if not loops.exists():
        write_atomic(loops, "# Active Loops\n")
        changed.append(LOOPS_FILE)
    for name, text in SKILLS.items():
        path = ws.path(f"{SKILLS_DIR}/{name}.md")
        if not path.exists():
            write_atomic(path, text)
            changed.append(f"{SKILLS_DIR}/{name}.md")

    config = global_config_path()
    if not config.exists():
        write_atomic(config, f"workspace = {root}\n")
        changed.append(str(config))
    return ws, changed
