"""Hermes adapter: skill pack + SOUL.md + knowledge bridge.

Rebuilt in the Phase B audit against verified Hermes facts (Nous Research,
hermes-agent v0.14.0):

  - Hermes' SOUL.md has no schema; the whole file is the soul. The adapter
    concatenates `knowledge/soul.md` + `knowledge/role-context.md` (with a
    header comment) and emits a plain markdown file.

  - Hermes' skills live at `~/.hermes/skills/<category>/<skill-name>/SKILL.md`
    with YAML frontmatter per the agentskills.io standard. AdzeKit's
    "category" is `adzekit`, and each core skill becomes
    `~/.hermes/skills/adzekit/<skill>/SKILL.md`. No pack.toml — that wasn't
    a Hermes concept.

  - Hermes provides no documented export schema for "what the agent learned
    about you" today. The previous pull direction silently no-op'd against
    a non-existent path; it now raises NotImplementedError pointing at
    Hermes' Honcho integration as the place to wire that up when it ships.

Cron and MCP-config sync are deferred: they require Hermes installed locally
to validate end-to-end. Nothing breaks today without them.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from adzekit.config import Settings, get_settings

_REPO_ROOT = Path(__file__).resolve().parents[3]
HERMES_PACK_DIR = _REPO_ROOT / "adapters" / "hermes" / "pack"
CORE_SKILLS_DIR = _REPO_ROOT / "src" / "adzekit" / "skills"

HERMES_HOME = Path.home() / ".hermes"
HERMES_SOUL_PATH = HERMES_HOME / "SOUL.md"
HERMES_SKILLS_DIR = HERMES_HOME / "skills" / "adzekit"
HERMES_CONTEXTS_DIR = HERMES_HOME / "contexts"
HERMES_KNOWLEDGE_CONTEXT = HERMES_CONTEXTS_DIR / "adzekit-knowledge.md"


# --- SOUL.md translation ----------------------------------------------------


def translate_soul_to_hermes(
    settings: Settings | None = None,
    *,
    dest: Path | None = None,
) -> Path | None:
    """Concat soul.md + role-context.md into a Hermes-compatible SOUL.md.

    Hermes treats the whole file as the agent's soul — no schema, no
    section parsing. The adapter therefore preserves the source content
    verbatim and only adds a small generated header noting provenance.

    Returns the destination path on success, or None when both source
    files are missing. When `dest` is None and `~/.hermes/` doesn't
    exist, the file is staged at `adapters/hermes/pack/SOUL.md`.
    """
    settings = settings or get_settings()
    soul_src = settings.knowledge_dir / "soul.md"
    role_src = settings.knowledge_dir / "role-context.md"

    parts: list[str] = []
    if soul_src.exists():
        parts.append(soul_src.read_text(encoding="utf-8").rstrip())
    if role_src.exists():
        parts.append(role_src.read_text(encoding="utf-8").rstrip())
    if not parts:
        return None

    body = "\n\n".join(parts)

    header = (
        "<!-- Generated by AdzeKit's Hermes adapter from "
        "knowledge/soul.md + knowledge/role-context.md.\n"
        "     Edit the AdzeKit sources and re-run `adzekit adapter install hermes`.\n"
        "     This file is overwritten on every install. -->\n\n"
    )

    target = dest if dest is not None else (
        HERMES_SOUL_PATH if HERMES_HOME.exists() else HERMES_PACK_DIR / "SOUL.md"
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(header + body.rstrip() + "\n", encoding="utf-8")
    return target


# --- Skill pack building ----------------------------------------------------


_AGENTSKILLS_LICENSE = "MIT"
_AGENTSKILLS_AUTHOR = "AdzeKit"
_AGENTSKILLS_VERSION = "0.4.0"


def _extract_description(skill_body: str) -> str:
    """Pull a one-line description from a skill's `## Goal` section.

    Falls back to a generic description if the skill doesn't follow the
    Goal/Inputs/Process/Outputs format.
    """
    lines = skill_body.splitlines()
    in_goal = False
    for line in lines:
        stripped = line.strip()
        if not in_goal:
            if stripped.lower().startswith("## goal"):
                in_goal = True
            continue
        if not stripped:
            continue
        if stripped.startswith("## "):
            break
        # First non-empty line under Goal is the description.
        return stripped[:240]
    # Fallback: first non-heading, non-empty line of the whole file.
    for line in lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            return stripped[:240]
    return "AdzeKit cognitive-prosthetic skill."


def _yaml_escape(value: str) -> str:
    """Wrap a string in double quotes and escape embedded quotes/newlines."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def _render_skill_md(name: str, body: str) -> str:
    """Wrap a core skill body in agentskills.io-style YAML frontmatter."""
    description = _extract_description(body)
    frontmatter = "\n".join([
        "---",
        f"name: {name}",
        f"description: {_yaml_escape(description)}",
        f"version: {_AGENTSKILLS_VERSION}",
        f"author: {_AGENTSKILLS_AUTHOR}",
        f"license: {_AGENTSKILLS_LICENSE}",
        "platforms:",
        "  - macos",
        "  - linux",
        "metadata:",
        "  source: AdzeKit core",
        "  homepage: https://github.com/AdzeKit/AdzeKit",
        "---",
        "",
    ])
    return frontmatter + body.lstrip("\n")


def build_skill_pack(*, pack_dir: Path | None = None) -> dict[str, Any]:
    """Build the Hermes skill pack at pack_dir/<skill>/SKILL.md.

    Each core skill markdown becomes its own subdirectory with a SKILL.md
    that has YAML frontmatter (per agentskills.io). The skill body
    follows the frontmatter unchanged.

    Returns metadata about the build (skill names, pack dir path).
    """
    pack_dir = pack_dir or HERMES_PACK_DIR
    pack_dir.mkdir(parents=True, exist_ok=True)

    # Clean stale per-skill directories from prior builds.
    for entry in list(pack_dir.iterdir()):
        if entry.is_dir():
            shutil.rmtree(entry)
        elif entry.is_file() and entry.suffix in (".md", ".toml"):
            # Drop pre-B-rebuild flat skills and the obsolete pack.toml.
            entry.unlink()

    copied: list[str] = []
    if CORE_SKILLS_DIR.exists():
        for src in sorted(CORE_SKILLS_DIR.glob("*.md")):
            skill_name = src.stem
            skill_dir = pack_dir / skill_name
            skill_dir.mkdir(parents=True, exist_ok=True)
            body = src.read_text(encoding="utf-8")
            (skill_dir / "SKILL.md").write_text(
                _render_skill_md(skill_name, body), encoding="utf-8",
            )
            copied.append(skill_name)

    return {
        "pack_dir": str(pack_dir),
        "skills": copied,
    }


# --- Install / uninstall / status ------------------------------------------


def install_hermes(settings: Settings | None = None) -> dict[str, Any]:
    """Build the pack, translate SOUL.md, mirror into ~/.hermes/ if present.

    When ~/.hermes/ exists, mirrors each `<skill>/SKILL.md` into
    `~/.hermes/skills/adzekit/<skill>/SKILL.md`. When Hermes isn't
    detected, the pack stays staged at `adapters/hermes/pack/` and the
    user can copy it manually.
    """
    settings = settings or get_settings()
    pack_info = build_skill_pack()
    soul_path = translate_soul_to_hermes(settings)

    hermes_skills_dir: str | None = None
    if HERMES_HOME.exists():
        # Wipe any prior install of the adzekit category and recreate.
        if HERMES_SKILLS_DIR.exists():
            shutil.rmtree(HERMES_SKILLS_DIR)
        HERMES_SKILLS_DIR.mkdir(parents=True, exist_ok=True)
        for skill_dir in Path(pack_info["pack_dir"]).iterdir():
            if not skill_dir.is_dir():
                continue
            dest = HERMES_SKILLS_DIR / skill_dir.name
            shutil.copytree(skill_dir, dest)
        hermes_skills_dir = str(HERMES_SKILLS_DIR)

    return {
        "adapter": "hermes",
        "pack_dir": pack_info["pack_dir"],
        "skills": pack_info["skills"],
        "soul_path": str(soul_path) if soul_path else None,
        "hermes_skills_dir": hermes_skills_dir,
    }


def uninstall_hermes() -> dict[str, Any]:
    """Remove the staged pack and any mirrored skills in ~/.hermes/."""
    pack_removed = False
    if HERMES_PACK_DIR.exists():
        shutil.rmtree(HERMES_PACK_DIR)
        pack_removed = True

    hermes_skills_removed: str | None = None
    if HERMES_SKILLS_DIR.exists():
        shutil.rmtree(HERMES_SKILLS_DIR)
        hermes_skills_removed = str(HERMES_SKILLS_DIR)

    # Leave ~/.hermes/SOUL.md in place — the user may have edited it.
    # Explicit purge would require a separate flag.

    return {
        "adapter": "hermes",
        "pack_dir": str(HERMES_PACK_DIR),
        "pack_removed": pack_removed,
        "hermes_skills_removed": hermes_skills_removed,
    }


def status_hermes(settings: Settings | None = None) -> dict[str, Any]:
    """Report the install state of the Hermes adapter."""
    settings = settings or get_settings()
    pack_present = HERMES_PACK_DIR.exists() and any(
        p.is_dir() and (p / "SKILL.md").exists()
        for p in HERMES_PACK_DIR.iterdir()
    ) if HERMES_PACK_DIR.exists() else False
    soul_translated = (HERMES_PACK_DIR / "SOUL.md").exists() or HERMES_SOUL_PATH.exists()
    soul_path = HERMES_SOUL_PATH if HERMES_SOUL_PATH.exists() else HERMES_PACK_DIR / "SOUL.md"
    hermes_present = HERMES_HOME.exists()
    hermes_skills_installed = (
        HERMES_SKILLS_DIR.exists()
        and any((p / "SKILL.md").exists() for p in HERMES_SKILLS_DIR.iterdir() if p.is_dir())
    )

    return {
        "adapter": "hermes",
        "pack_dir": str(HERMES_PACK_DIR),
        "pack_present": pack_present,
        "soul_path": str(soul_path),
        "soul_translated": soul_translated,
        "hermes_detected": hermes_present,
        "hermes_skills_installed": hermes_skills_installed,
    }


# --- Knowledge bridge -------------------------------------------------------
#
# Why bridge (not replace): Hermes' Honcho user model is opaque (embedding
# store). AdzeKit's knowledge/ is markdown — readable, diffable, editable in
# any text editor, recoverable from git log. Replacing knowledge/ with
# Honcho would violate Principle 7 (Legibility Over Memory) and collapse
# the distinction between "I wrote this" and "the agent inferred this."
#
# Push (knowledge → Hermes context) is implemented; the file lands at
# ~/.hermes/contexts/adzekit-knowledge.md so Hermes reads it as persistent
# session context.
#
# Pull (Hermes-inferred → drafts/) is NOT implemented and now fails loud.
# Hermes has no documented export schema for "what the agent learned about
# you." When/if it ships one (likely via the optional Honcho integration),
# this is the place to wire it up — the draft-proposal contract is already
# documented in docs/hermes-integration.md.


def push_knowledge_to_hermes(
    settings: Settings | None = None,
    *,
    dest: Path | None = None,
) -> dict[str, Any]:
    """Concatenate knowledge/*.md into a Hermes context file.

    Returns metadata about what was pushed. Returns an empty result when
    knowledge/ has no .md files.
    """
    settings = settings or get_settings()
    knowledge = settings.knowledge_dir
    if not knowledge.exists():
        return {"pushed": False, "reason": "knowledge_dir_missing"}

    files = sorted(knowledge.glob("*.md"))
    if not files:
        return {"pushed": False, "reason": "no_knowledge_files", "files": []}

    target = dest if dest is not None else (
        HERMES_KNOWLEDGE_CONTEXT if HERMES_HOME.exists()
        else HERMES_PACK_DIR / "contexts" / "adzekit-knowledge.md"
    )
    target.parent.mkdir(parents=True, exist_ok=True)

    parts: list[str] = [
        "# AdzeKit Knowledge Context",
        "",
        "_Concatenated from `knowledge/*.md` by AdzeKit's Hermes adapter._",
        "_Edit the AdzeKit source notes; this file is regenerated on push._",
        "",
    ]
    pushed_files: list[str] = []
    for path in files:
        # soul.md and role-context.md flow through SOUL.md instead of here.
        if path.name in ("soul.md", "role-context.md"):
            continue
        slug = path.stem
        parts.append(f"## {slug}")
        parts.append("")
        parts.append(f"_Source: `knowledge/{path.name}`_")
        parts.append("")
        parts.append(path.read_text(encoding="utf-8").strip())
        parts.append("")
        pushed_files.append(path.name)
    target.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")

    return {
        "pushed": True,
        "target": str(target),
        "files": pushed_files,
    }


class HermesExportNotImplementedError(NotImplementedError):
    """Raised by pull_inferences_from_hermes — Hermes has no export schema yet.

    When Hermes ships a documented user-inferences export (most likely via
    the Honcho integration), wire it up here. The contract is documented:
    the export is read, wrapped with a "review before promoting" header,
    and routed to drafts/knowledge/ as a normal draft proposal with full
    provenance — subject to `adzekit drafts accept` like any other draft.

    See docs/hermes-integration.md "Knowledge: bridge, not replace" for
    the design.
    """


def pull_inferences_from_hermes(
    settings: Settings | None = None,
    *,
    export_path: Path | None = None,
) -> dict[str, Any]:
    """Pull direction of the bridge — currently raises (no Hermes export schema).

    Pre-fix this silently no-op'd when the placeholder export path didn't
    exist, which was indistinguishable from "Hermes has nothing for me
    today." Now raises HermesExportNotImplementedError with a clear
    explanation so the user knows the feature is intentionally stubbed.
    """
    raise HermesExportNotImplementedError(
        "Hermes does not currently publish a documented export schema for "
        "user inferences. The pull direction of the bridge is intentionally "
        "stubbed until it does (likely via Hermes' optional Honcho "
        "integration). The draft-proposal contract is already defined in "
        "docs/hermes-integration.md — wire it up there when Hermes ships."
    )


def sync_hermes(
    settings: Settings | None = None,
    *,
    direction: str = "push",
) -> dict[str, Any]:
    """Run the bridge. `direction` is now push-only by default.

    Pull raises HermesExportNotImplementedError. `direction="both"` runs
    push and then fails fast on pull — the test suite uses this to verify
    the error message.
    """
    settings = settings or get_settings()
    result: dict[str, Any] = {"adapter": "hermes", "direction": direction}
    if direction in ("push", "both"):
        result["push"] = push_knowledge_to_hermes(settings)
    if direction in ("pull", "both"):
        # Surface the not-implemented error rather than silently no-op'ing.
        result["pull"] = pull_inferences_from_hermes(settings)
    return result
